import {currentIndexAt,makeSchedule} from './schedule.js';
import {decodeLineup,encodeLineup} from './lineup-share.js';
import {availableThemes,buildThemedChannels,GENRES,normalizeTags} from './themes.js';

let installPrompt=null;
window.addEventListener('beforeinstallprompt',event=>{
  event.preventDefault();
  installPrompt=event;
  document.querySelector('#install-app')?.classList.remove('hidden');
});
window.addEventListener('appinstalled',()=>{
  installPrompt=null;
  document.querySelector('#install-app')?.classList.add('hidden');
});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
const DEMO_CHANNELS=[
 {n:2,name:'INTERNET CLASSICS',color:'#52d9db',shows:[['Me at the Zoo','jawed','jNQXAC9IVRw',19],['Keyboard Cat','Keyboard Cat','J---aiyznGQ',54],['Never Gonna Give You Up','Rick Astley','dQw4w9WgXcQ',213],['The Duck Song','forrestfire101','MtN1YnoL46Q',191],['Numa Numa','Internet Archive','KmtzQCSh6xk',218]]},
 {n:3,name:'BIG SCREEN',color:'#ed6a5a',shows:[['Big Buck Bunny','Blender Animation Studio','aqz-KE-bpKQ',596],['Sintel','Blender Animation Studio','eRsGyueVLvQ',888],['Tears of Steel','Blender Animation Studio','R6MlUcmOul8',734],['Cosmos Laundromat','Blender Animation Studio','Y-rmzh0PI3c',734]]},
 {n:4,name:'MUSIC TELEVISION',color:'#f2bd56',shows:[['Take On Me','a-ha','djV11Xbc914',225],['Virtual Insanity','Jamiroquai','4JkIs37a2JE',234],['Weapon of Choice','Fatboy Slim','wCDIYvFmgW8',232],['Around the World','Daft Punk','K0HSD_i2DvA',247],['Sabotage','Beastie Boys','z5rRZdiu1UE',183]]},
 {n:5,name:'ODDITIES',color:'#b18cff',shows:[['YouTube Player API Demo','YouTube Developers','M7lc1UVf-VE',410],['Charlie the Unicorn','FilmCow','CsGYh8AacgY',226],['Potter Puppet Pals','Neil Cicierega','Tx1XIm6q4r4',125],['Badger Badger Badger','Weebl','EIyixC9NsLI',196]]},
 {n:6,name:'LATE NIGHT',color:'#ff779d',shows:[['Chocolate Rain','Tay Zonday','EwTZ2xpQwpA',292],['Shoes','Liam Kyle Sullivan','wCF3ywukQYA',241],['Dramatic Chipmunk','Internet Classic','a1Y73sPHKxw',64],['Double Rainbow','Yosemitebear62','OQSNhk5ICTI',207],['The Ultimate Showdown','Lemon Demon','lrzKT-dFUjE',213]]},
 {n:7,name:'LOUNGE',color:'#75d887',shows:[['Lofi Study Session','Demo Channel','jfKfPfyJRdk',3600],['Relaxing Visuals','Demo Channel','5qap5aO4i9A',3600],['Night Drive','Demo Channel','DWcJFNfaw9c',3600]]}
];
let CHANNELS=[];
try{CHANNELS=JSON.parse(localStorage.getItem('elsewhere-channels')||'null')||structuredClone(DEMO_CHANNELS)}catch{CHANNELS=structuredClone(DEMO_CHANNELS)}
const state={row:0,col:0,guide:true,player:null,ready:false,current:null,previousRow:null,muted:false,bannerTimer:null,remoteTimer:null,interstitialTimer:null,interstitialShownAt:0,interstitialPending:false,upNextKey:''};
function scheduleChannels(){CHANNELS.forEach(c=>c.schedule=makeSchedule(c))}
function sourceChannels(){return CHANNELS.filter(channel=>!channel.isThemed)}
let disabledThemes=new Set(JSON.parse(localStorage.getItem('fake-cable-disabled-themes')||'[]'));
function rebuildThemedChannels(){const sources=sourceChannels();CHANNELS=[...sources,...buildThemedChannels(sources,stationPicker,[...disabledThemes])];CHANNELS.forEach((channel,index)=>channel.n=index+2);scheduleChannels()}
scheduleChannels();
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nowSec=()=>Date.now()/1000;
function currentIndex(ch){return currentIndexAt(ch,nowSec())}
function fmtClock(s){return new Date(s*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function guideSlotWidth(){return Math.min(300,Math.max(190,window.innerWidth*.17))}
function render(){const start=Math.floor(nowSec()/1800)*1800-1800,end=start+10800;const timeline=document.querySelector('#timeline');timeline.innerHTML='<div class="timeline-corner"></div>'+Array.from({length:6},(_,i)=>`<div class="time-label">${fmtClock(start+i*1800)}</div>`).join('');const pxPerSec=(timeline.querySelector('.time-label')?.getBoundingClientRect().width||guideSlotWidth())/1800;
 const grid=document.querySelector('#grid');grid.innerHTML='';CHANNELS.forEach((ch,ri)=>{const row=document.createElement('div');row.className='channel-row'+(ri===state.row?' selected':'');row.dataset.row=ri;const programs=ch.schedule.filter(p=>p.end>start&&p.start<end);const current=ch.schedule[currentIndex(ch)];row.innerHTML=`<div class="channel-num" data-tune="${ri}" style="color:${ch.color}">${String(ch.n).padStart(2,'0')}<small>${esc(ch.name)}</small></div><div class="programs"></div>`;const box=row.lastElementChild;programs.forEach(p=>{const idx=ch.schedule.indexOf(p),el=document.createElement('div');el.className='program'+(p===current?' current':'')+(ri===state.row&&idx===state.col?' focused':'');el.dataset.row=ri;el.dataset.col=idx;el.style.left=Math.max(0,(p.start-start)*pxPerSec)+'px';el.style.width=Math.max(80,(Math.min(p.end,end)-Math.max(p.start,start))*pxPerSec-4)+'px';el.innerHTML=`<div class="program-title">${esc(p.title)}</div><div class="program-source">${esc(p.source)}</div>${p===current?'<div class="live">ON NOW</div>':''}`;box.appendChild(el)});grid.appendChild(row)});updateSelection(false)}
function ensureSelection(){const ch=CHANNELS[state.row];if(state.col<0||state.col>=ch.schedule.length||ch.schedule[state.col].end<nowSec()-1800||ch.schedule[state.col].start>nowSec()+10800)state.col=currentIndex(ch)}
function updateSelection(scroll=true){ensureSelection();const ch=CHANNELS[state.row],p=ch.schedule[state.col];document.querySelector('#selected-title').textContent=p.title;document.querySelector('#selected-meta').textContent=`CH ${String(ch.n).padStart(2,'0')} · ${ch.name} · ${fmtClock(p.start)}–${fmtClock(p.end)}`;document.querySelectorAll('.channel-row').forEach((r,i)=>r.classList.toggle('selected',i===state.row));document.querySelectorAll('.program').forEach(e=>e.classList.remove('focused'));const row=document.querySelectorAll('.channel-row')[state.row];if(row){const focused=row.querySelector(`.program[data-col="${state.col}"]`);focused?.classList.add('focused');if(scroll){row.scrollIntoView({block:'nearest'});focused?.scrollIntoView({block:'nearest',inline:'nearest'})}}}
function broadcastOffset(p){return Math.max(0,Math.min(p.duration-1,Math.floor(nowSec()-p.start)))}
function showInterstitial(ch,p){const panel=document.querySelector('#interstitial');clearTimeout(state.interstitialTimer);state.interstitialShownAt=Date.now();state.interstitialPending=true;panel.style.setProperty('--station-color',ch.color||'#52d9db');document.querySelector('#interstitial-title').textContent=p.title;document.querySelector('#interstitial-channel').textContent=`CH ${String(ch.n).padStart(2,'0')}`;document.querySelector('#interstitial-station').textContent=ch.name;panel.classList.add('show');state.interstitialTimer=setTimeout(()=>hideInterstitial(),6000)}
function hideInterstitial(force=false){const panel=document.querySelector('#interstitial');clearTimeout(state.interstitialTimer);if(!panel.classList.contains('show')){state.interstitialPending=false;return}const wait=force?0:Math.max(0,1400-(Date.now()-state.interstitialShownAt));state.interstitialTimer=setTimeout(()=>{panel.classList.remove('show');const announce=state.interstitialPending;state.interstitialPending=false;if(announce&&!state.guide)showBanner()},wait)}
function loadCurrentProgram(){if(!state.ready||!state.current)return;const {p}=state.current;state.player.loadVideoById({videoId:p.id,startSeconds:broadcastOffset(p)});if(state.muted)state.player.mute()}
function syncActualDuration(){if(!state.current||!state.ready)return;const actual=Math.round(state.player.getDuration?.()||0);if(actual<1)return;const {ch,p}=state.current;if(Math.abs(actual-p.duration)<=2)return;const played=Math.max(0,Math.min(actual-1,state.player.getCurrentTime?.()||0));p.duration=actual;p.start=nowSec()-played;p.end=p.start+actual;let cursor=p.end,index=ch.schedule.indexOf(p);for(let i=index+1;i<ch.schedule.length;i++){ch.schedule[i].start=cursor;ch.schedule[i].end=cursor+ch.schedule[i].duration;cursor=ch.schedule[i].end}const show=ch.shows.find(item=>item[2]===p.id);if(show)show[3]=actual;try{localStorage.setItem('elsewhere-channels',JSON.stringify(CHANNELS.map(({schedule,...channel})=>channel)))}catch{}if(state.guide)render();showBanner()}
function tune(row=state.row){hideInterstitial(true);const next=(row+CHANNELS.length)%CHANNELS.length;if(state.current&&next!==state.row)state.previousRow=state.row;state.row=next;const ch=CHANNELS[state.row];state.col=currentIndex(ch);const p=ch.schedule[state.col],alreadyTuned=state.current?.row===state.row&&state.current?.p?.id===p.id;state.current={row:state.row,index:state.col,ch,p};if(!alreadyTuned)loadCurrentProgram();showGuide(false);showBanner();localStorage.setItem('elsewhere-last-channel',String(state.row))}
function advanceAfterEnd(){if(!state.current)return;const {row,ch,p}=state.current,index=ch.schedule.indexOf(p);if(index<0){tune(row);return}const endedAt=nowSec();if(endedAt<p.end-1){p.end=endedAt;let cursor=endedAt;for(let i=index+1;i<ch.schedule.length;i++){ch.schedule[i].start=cursor;ch.schedule[i].end=cursor+ch.schedule[i].duration;cursor=ch.schedule[i].end}}const nextIndex=Math.min(index+1,ch.schedule.length-1);state.row=row;state.col=nextIndex;state.current={row,index:nextIndex,ch,p:ch.schedule[nextIndex]};if(state.guide)render();else showInterstitial(ch,ch.schedule[nextIndex]);loadCurrentProgram()}
function skipUnavailableProgram(){if(!state.current)return;const {row,ch,p}=state.current;if(ch.isThemed){for(const source of sourceChannels()){if(source.shows.some(show=>show[2]===p.id)){source.unavailableIds=[...new Set([...(source.unavailableIds||[]),p.id])];source.shows=source.shows.filter(show=>show[2]!==p.id)}}rebuildThemedChannels()}else{ch.unavailableIds=[...new Set([...(ch.unavailableIds||[]),p.id])];ch.shows=ch.shows.filter(show=>show[2]!==p.id)}saveLineup();if(!ch.shows.length){toast('CHANNEL TEMPORARILY OFF AIR');showGuide(true);return}const tuned=CHANNELS.findIndex(channel=>channel.channelId===ch.channelId);state.current=null;tune(tuned<0?0:tuned)}
function showGuide(on){state.guide=on;document.querySelector('#guide').classList.toggle('hidden',!on);if(on){render();document.querySelector('#grid-scroll').focus()}}
function showBanner(){if(!state.current)return;const {ch,p}=state.current,elapsed=Math.max(0,nowSec()-p.start);document.querySelector('#banner-channel').textContent=`CH ${String(ch.n).padStart(2,'0')}  ·  ${ch.name}`;document.querySelector('#banner-title').textContent=p.title;document.querySelector('#banner-meta').textContent=`${p.source}  ·  ${Math.floor(elapsed/60)} MINUTES INTO PROGRAM` ;document.querySelector('#banner-progress').style.width=Math.min(100,elapsed/p.duration*100)+'%';const b=document.querySelector('#banner');b.classList.add('show');clearTimeout(state.bannerTimer);state.bannerTimer=setTimeout(()=>b.classList.remove('show'),4200)}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function setRemoteMinimized(on){const remote=document.querySelector('#remote'),button=remote.querySelector('.minimize');remote.classList.toggle('minimized',on);button.textContent=on?'REMOTE':'−';button.setAttribute('aria-label',on?'Show on-screen controls':'Minimize on-screen controls');button.title=on?'Show controls':'Minimize controls';clearTimeout(state.remoteTimer);if(!on)scheduleRemoteHide()}
function scheduleRemoteHide(){clearTimeout(state.remoteTimer);if(document.querySelector('#welcome').style.display!=='none'||document.querySelector('#setup').style.display==='block')return;state.remoteTimer=setTimeout(()=>setRemoteMinimized(true),8000)}
function stepProgram(dir){const ch=CHANNELS[state.row];state.col=Math.max(0,Math.min(ch.schedule.length-1,state.col+dir));render()}
function tick(){const d=new Date();document.querySelector('#time').textContent=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});document.querySelector('#date').textContent=d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}).toUpperCase();if(!state.current)return;const remaining=state.current.p.end-nowSec();if(remaining<=0){state.upNextKey='';tune(state.row);return}const {ch,p}=state.current,index=ch.schedule.indexOf(p),next=ch.schedule[index+1],key=`${ch.channelId||ch.name}:${p.id}:${p.start}`;if(next&&remaining<=60&&state.upNextKey!==key){state.upNextKey=key;toast(`UP NEXT · ${next.title}`)}}
const setupStatus=msg=>document.querySelector('#setup-status').textContent=msg;
let stationPicker=[];
let stationUpdating=false;
let expandedGenreIndex=null;
try{stationPicker=JSON.parse(localStorage.getItem('fake-cable-stations')||'null')||(localStorage.getItem('elsewhere-channel-links')||'').split(/\r?\n/).filter(Boolean).map(value=>({value,label:value,tags:[]}));stationPicker=stationPicker.map(station=>({...station,tags:normalizeTags(station.tags)}));rebuildThemedChannels()}catch{}
function openSetup(){document.querySelector('#setup').style.display='block';setupStatus('');document.querySelector('#search-results').innerHTML='';renderStationPicker()}
function closeSetup(){document.querySelector('#setup').style.display='none';expandedGenreIndex=null}
function channelSummary(channel){if(!channel)return 'Not loaded yet';const seconds=channel.shows.reduce((sum,show)=>sum+(Number(show[3])||0),0),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);const age=channel.updatedAt?Math.max(0,Math.floor((Date.now()-channel.updatedAt)/86400000)):null;const updated=age===null?'Update pending':age===0?'Updated today':age===1?'Updated yesterday':`Updated ${age} days ago`;return `${channel.shows.length} videos · ${hours?hours+'h ':''}${minutes}m · ${channel.refreshError?'Refresh failed—using saved lineup':updated}`}
function renderStationPicker(){const sources=sourceChannels(),box=document.querySelector('#station-list');document.querySelector('#station-count').textContent=`CREATOR CHANNELS · ${stationPicker.length}/30`;box.innerHTML=stationPicker.length?stationPicker.map((station,index)=>{const tags=normalizeTags(station.tags),expanded=expandedGenreIndex===index,summary=tags.length?tags.map(key=>GENRES.find(genre=>genre.key===key)?.label).filter(Boolean).join(', '):'None';return `<div class="station-item"><div class="station-copy"><strong>${esc(station.label)}</strong><div class="station-details">${esc(channelSummary(sources[index]))}</div></div><button data-refresh="${index}" ${stationUpdating?'disabled':''}>REFRESH</button><button data-remove="${index}" ${stationUpdating?'disabled':''}>REMOVE</button><div class="genre-summary-row"><div><span>THEMED CHANNELS</span><strong>${esc(summary)}</strong></div><button class="genre-expand" data-genre-expand="${index}" aria-expanded="${expanded}">${expanded?'DONE':'EDIT'} ${expanded?'▴':'▾'}</button></div><div class="genre-picker ${expanded?'':'collapsed'}">${GENRES.map(genre=>`<button class="genre-chip ${tags.includes(genre.key)?'active':''}" data-station-tag="${index}" data-genre="${genre.key}">${genre.label}</button>`).join('')}</div></div>`}).join(''):'<div class="setup-note">You’re using the starter lineup.</div>';renderThemePicker()}
function renderThemePicker(){const themes=availableThemes(sourceChannels(),stationPicker),box=document.querySelector('#theme-list');document.querySelector('#theme-count').textContent=`THEMED CHANNELS · ${themes.length}`;box.innerHTML=themes.length?themes.map(theme=>`<div class="theme-item" style="--theme-color:${theme.color}"><div class="theme-copy"><strong>${esc(theme.name)}</strong><small>${theme.sourceCount} creator sources</small></div><button class="theme-toggle ${disabledThemes.has(theme.key)?'off':''}" data-theme-toggle="${theme.key}">${disabledThemes.has(theme.key)?'OFF':'ON'}</button></div>`).join(''):'<div class="setup-note">Tag at least two creators with the same genre to create a themed channel.</div>'}
async function fetchStationChannel(value) {
  const res=await fetch('/api/channels',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({channels:[value]})});
  const data=await res.json();
  if(!res.ok||!data.channels?.length)throw new Error(data.error||'Could not build that channel.');
  return data.channels[0];
}
function channelFromApi(channel,index,existing=null) {
  const colors=['#52d9db','#ed6a5a','#f2bd56','#b18cff','#ff779d','#75d887','#63a7ff','#f58f54'],unavailableIds=existing?.unavailableIds||[];
  return {n:index+2,name:channel.name.toUpperCase(),channelId:channel.channelId,color:existing?.color||colors[index%colors.length],shows:channel.shows.filter(v=>!unavailableIds.includes(v.id)).map(v=>[v.title,channel.name,v.id,v.duration]),unavailableIds,updatedAt:Date.now(),lastAttemptAt:Date.now(),refreshError:false};
}
function saveLineup(){const sources=sourceChannels();CHANNELS.forEach((channel,index)=>channel.n=index+2);localStorage.setItem('elsewhere-channel-links',stationPicker.map(s=>s.value).join('\n'));localStorage.setItem('fake-cable-stations',JSON.stringify(stationPicker));localStorage.setItem('elsewhere-channels',JSON.stringify(sources.map(({schedule,...channel})=>channel)));localStorage.setItem('fake-cable-lineup-version','5');document.querySelector('#lineup-status').textContent=`${sources.length} creator channels · ${CHANNELS.length-sources.length} themed`}
async function addStation(value,label=value){if(stationUpdating)return;if(stationPicker.length>=30){setupStatus('The cable package is full at 30 channels.');return}if(stationPicker.some(s=>s.value===value)){setupStatus('That channel is already in your lineup.');return}stationUpdating=true;const wasEmpty=!stationPicker.length;stationPicker.push({value,label,tags:[]});renderStationPicker();document.querySelector('#search-channel').disabled=true;setupStatus(`Adding ${label}…`);try{const channel=await fetchStationChannel(value);if(wasEmpty)CHANNELS=[];else CHANNELS=sourceChannels();const built=channelFromApi(channel,CHANNELS.length);CHANNELS.push(built);rebuildThemedChannels();saveLineup();setupStatus(`${label} added. Optionally choose genres below, or close Settings to watch.`)}catch(err){stationPicker.pop();renderStationPicker();setupStatus(err.message)}finally{stationUpdating=false;document.querySelector('#search-channel').disabled=false;renderStationPicker()}}
async function refreshStation(index,{quiet=false}={}){const station=stationPicker[index],existing=CHANNELS[index];if(!station||!existing)return false;if(!quiet){stationUpdating=true;renderStationPicker();setupStatus(`Refreshing ${station.label}…`)}try{const channel=await fetchStationChannel(station.value),updated=channelFromApi(channel,index,existing);updated.schedule=makeSchedule(updated);const wasCurrent=state.current?.row===index;CHANNELS[index]=updated;rebuildThemedChannels();if(wasCurrent){state.row=index;state.col=currentIndex(updated);const p=updated.schedule[state.col];state.current={row:index,index:state.col,ch:updated,p};loadCurrentProgram()}saveLineup();if(!quiet)setupStatus(`${station.label} refreshed.`);if(state.guide)render();return true}catch(err){existing.lastAttemptAt=Date.now();existing.refreshError=true;saveLineup();if(!quiet)setupStatus(`Could not refresh ${station.label}. Keeping its saved lineup.`);return false}finally{if(!quiet){stationUpdating=false;document.querySelector('#search-channel').disabled=false;renderStationPicker()}}}
async function refreshStaleChannels(){if(stationUpdating)return;for(let i=0;i<stationPicker.length;i++){const channel=CHANNELS[i];if(!channel||Date.now()-(channel.updatedAt||0)<86400000)continue;await refreshStation(i,{quiet:true});renderStationPicker();if(i<stationPicker.length-1)await new Promise(resolve=>setTimeout(resolve,500))}}
async function searchChannel(){const input=document.querySelector('#channel-search'),query=input.value.trim();if(!query){setupStatus('Type a creator name or paste a YouTube link.');return}if(/(?:youtube\.com|youtu\.be|^@)/i.test(query)){addStation(query,query);input.value='';return}const button=document.querySelector('#search-channel');button.disabled=true;setupStatus(`Searching YouTube for “${query}”…`);try{const res=await fetch('/api/channels',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'search',query})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Search failed.');document.querySelector('#search-results').innerHTML=data.results.map(r=>`<div class="search-result"><img src="${esc(r.thumb)}" alt=""><strong>${esc(r.title)}</strong><button data-add-url="${esc(r.url)}" data-add-label="${esc(r.title)}">ADD</button></div>`).join('');setupStatus(`${data.results.length} channel results.`)}catch(err){setupStatus(err.message)}finally{button.disabled=false}}
async function buildChannels(successMessage='Lineup updated.'){if(stationUpdating)return;stationUpdating=true;renderStationPicker();document.querySelector('#search-channel').disabled=true;try{if(!stationPicker.length){CHANNELS=structuredClone(DEMO_CHANNELS);scheduleChannels();disabledThemes.clear();localStorage.removeItem('fake-cable-disabled-themes');localStorage.removeItem('elsewhere-channel-links');localStorage.removeItem('elsewhere-channels');localStorage.removeItem('fake-cable-stations');localStorage.removeItem('fake-cable-lineup-version');document.querySelector('#lineup-status').textContent='Starter lineup ready'}else{const rebuilt=[],workingStations=[],total=stationPicker.length;let failed=0;for(let i=0;i<total;i++){const station=stationPicker[i];setupStatus(`Refreshing channel ${i+1} of ${total}…`);document.querySelector('#lineup-status').textContent=`Refreshing channel ${i+1} of ${total}…`;try{const channel=await fetchStationChannel(station.value);rebuilt.push(channelFromApi(channel,rebuilt.length));workingStations.push(station)}catch{failed++;const saved=CHANNELS[i];if(saved?.shows?.length){saved.n=rebuilt.length+2;saved.refreshError=true;saved.lastAttemptAt=Date.now();rebuilt.push(saved);workingStations.push(station)}}if(i<total-1)await new Promise(resolve=>setTimeout(resolve,250))}if(!rebuilt.length)throw new Error('YouTube could not refresh any channels right now. Your saved lineup was not changed.');stationPicker=workingStations;CHANNELS=rebuilt;rebuildThemedChannels();saveLineup();if(failed)successMessage+=` ${failed} channel${failed===1?'':'s'} could not refresh, so saved programming was kept.`}state.row=Math.min(state.row,CHANNELS.length-1);state.col=currentIndex(CHANNELS[state.row]);state.current=null;state.previousRow=null;setupStatus(`${successMessage} Opening the guide…`);setTimeout(()=>{closeSetup();showGuide(true)},500);return true}catch(err){setupStatus(err.message);return false}finally{stationUpdating=false;document.querySelector('#search-channel').disabled=false;renderStationPicker()}}
window.onYouTubeIframeAPIReady=()=>{const hosted=/^https?:$/.test(location.protocol);state.player=new YT.Player('player',{width:'100%',height:'100%',playerVars:{autoplay:1,controls:1,rel:0,playsinline:1,...(hosted?{origin:location.origin}:{})},events:{onReady:()=>{state.ready=true;loadCurrentProgram()},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED)advanceAfterEnd();else if(e.data===YT.PlayerState.PLAYING&&state.current){const actual=state.player.getVideoData()?.video_id;if(actual&&actual!==state.current.p.id)loadCurrentProgram();else{syncActualDuration();if(state.interstitialPending)hideInterstitial()}}},onError:e=>{hideInterstitial(true);if(e.data===153||!hosted){document.querySelector('#playback-error').style.display='flex'}else if([2,100,101,150].includes(e.data)){toast('PROGRAM UNAVAILABLE — SKIPPING AHEAD');setTimeout(skipUnavailableProgram,700)}else toast(`Video unavailable here (error ${e.data}) — try another channel`)}}})};
let sharedUrl='',incoming=null;function modal(v){document.querySelector('#lineup-modal').style.display='block';document.querySelector('#share-lineup-view').classList.toggle('hidden',v!=='share');document.querySelector('#import-lineup-view').classList.toggle('hidden',v!=='import')}function shareLineup(){try{const es=CHANNELS.map((c,i)=>[c.channelId,stationPicker[i]?.label||c.name]).filter(x=>x[0]);sharedUrl=`${location.origin}${location.pathname}#lineup=${encodeLineup(es)}`;const q=document.querySelector('#lineup-qr');q.innerHTML='';new QRCode(q,{text:sharedUrl,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});document.querySelector('#native-share-lineup').classList.toggle('hidden',!navigator.share);modal('share')}catch(e){setupStatus(e.message)}}function incomingLineup(d){incoming=d.channels;history.replaceState(null,'',location.pathname+location.search);document.querySelector('#lineup-modal-title').textContent='Shared lineup found';document.querySelector('#import-lineup-summary').textContent=`${incoming.length} channels are ready. Add missing channels or replace this device’s lineup.`;document.querySelector('#incoming-lineup-list').innerHTML=incoming.map((x,i)=>`<div class="incoming-item"><span class="incoming-number">${i+1}</span><span class="incoming-name">${esc(x[1])}</span></div>`).join('');modal('import')}async function importLineup(mode){if(stationUpdating)return;const ids=new Set(CHANNELS.map(c=>c.channelId)),todo=mode==='add'?incoming.filter(x=>!ids.has(x[0])):incoming,status=document.querySelector('#import-lineup-status');if(!todo.length){status.textContent='Every shared channel is already here.';return}stationUpdating=true;const keep=mode==='add'&&stationPicker.length,ns=keep?[...stationPicker]:[],nc=keep?[...CHANNELS]:[];let failed=0;for(let i=0;i<todo.length;i++){status.textContent=`Loading channel ${i+1} of ${todo.length}…`;try{const c=await fetchStationChannel(todo[i][0]);ns.push({value:todo[i][0],label:todo[i][1],tags:normalizeTags(todo[i][2])});nc.push(channelFromApi(c,nc.length))}catch{failed++}}stationUpdating=false;const added=ns.length-(keep?stationPicker.length:0);if(!added){status.textContent='YouTube could not load these channels. Your lineup was not changed.';return}stationPicker=ns.slice(0,30);CHANNELS=nc.slice(0,30);rebuildThemedChannels();saveLineup();state.row=0;state.current=null;status.textContent=`${added} imported${failed?`, ${failed} skipped`:''}.`;setTimeout(()=>document.querySelector('#lineup-modal').style.display='none',900)}

document.querySelector('#install-app').onclick=async()=>{
  if(!installPrompt)return;
  installPrompt.prompt();
  await installPrompt.userChoice;
  installPrompt=null;
  document.querySelector('#install-app').classList.add('hidden');
};
document.querySelector('#start').onclick=()=>{document.querySelector('#welcome').style.display='none';const last=Number(localStorage.getItem('elsewhere-last-channel')||0);state.row=Math.min(CHANNELS.length-1,Math.max(0,last));render();tune(state.row);scheduleRemoteHide()};
document.querySelector('#grid').addEventListener('click',e=>{const tuneTarget=e.target.closest('[data-tune]');if(tuneTarget){tune(Number(tuneTarget.dataset.tune));return}const card=e.target.closest('.program');if(!card)return;state.row=Number(card.dataset.row);state.col=Number(card.dataset.col);const isNow=state.col===currentIndex(CHANNELS[state.row]);render();if(isNow)tune(state.row)});
document.querySelector('#remote').addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.action;if(!action)return;if(action==='controls'){setRemoteMinimized(!e.currentTarget.classList.contains('minimized'));return}scheduleRemoteHide();if(action==='guide')showGuide(!state.guide);if(action==='up')tune(state.row+1);if(action==='down')tune(state.row-1);if(action==='watch')tune(state.row);if(action==='settings')openSetup();if(action==='mute'&&state.ready){state.muted=!state.muted;state.muted?state.player.mute():state.player.unMute();toast(state.muted?'MUTED':'SOUND ON')}if(action==='last'){if(state.previousRow===null){toast('NO PREVIOUS CHANNEL');return}const last=state.previousRow;tune(last)}if(action==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>toast('FULLSCREEN BLOCKED BY BROWSER'))}});
document.querySelector('#remote').addEventListener('pointermove',()=>{if(!document.querySelector('#remote').classList.contains('minimized'))scheduleRemoteHide()});
document.querySelector('#close-setup').onclick=closeSetup;
document.querySelector('#back-to-guide').onclick=()=>{document.querySelector('#playback-error').style.display='none';showGuide(true)};
document.querySelector('#search-channel').onclick=searchChannel;
document.querySelector('#share-lineup').onclick=shareLineup;document.querySelector('#about-help').onclick=()=>document.querySelector('#about-modal').style.display='block';document.querySelector('#close-about').onclick=()=>document.querySelector('#about-modal').style.display='none';document.querySelector('#close-lineup-modal').onclick=()=>document.querySelector('#lineup-modal').style.display='none';document.querySelector('#copy-lineup-link').onclick=()=>navigator.clipboard.writeText(sharedUrl);document.querySelector('#native-share-lineup').onclick=()=>navigator.share?.({title:'Fake Cable lineup',url:sharedUrl});document.querySelector('#add-shared-lineup').onclick=()=>importLineup('add');document.querySelector('#replace-with-shared-lineup').onclick=()=>importLineup('replace');document.querySelector('#clear-stations').onclick=()=>{if(stationUpdating)return;stationPicker=[];renderStationPicker();buildChannels('Starter lineup restored.')};
document.querySelector('#search-results').addEventListener('click',e=>{const button=e.target.closest('[data-add-url]');if(button)addStation(button.dataset.addUrl,button.dataset.addLabel)});
document.querySelector('#station-list').addEventListener('click',e=>{const expand=e.target.closest('[data-genre-expand]');if(expand&&!stationUpdating){const index=Number(expand.dataset.genreExpand);expandedGenreIndex=expandedGenreIndex===index?null:index;renderStationPicker();return}const tag=e.target.closest('[data-station-tag]');if(tag&&!stationUpdating){const index=Number(tag.dataset.stationTag),genre=tag.dataset.genre,tags=new Set(normalizeTags(stationPicker[index].tags));tags.has(genre)?tags.delete(genre):tags.add(genre);stationPicker[index].tags=[...tags];CHANNELS=sourceChannels();rebuildThemedChannels();saveLineup();state.current=null;renderStationPicker();render();return}const refresh=e.target.closest('[data-refresh]');if(refresh&&!stationUpdating){refreshStation(Number(refresh.dataset.refresh));return}const button=e.target.closest('[data-remove]');if(!button||stationUpdating)return;const index=Number(button.dataset.remove);stationPicker.splice(index,1);CHANNELS=sourceChannels();CHANNELS.splice(index,1);if(!stationPicker.length){buildChannels('Starter lineup restored.');return}rebuildThemedChannels();saveLineup();state.row=Math.min(state.row,CHANNELS.length-1);state.col=currentIndex(CHANNELS[state.row]);state.current=null;renderStationPicker();setupStatus('Channel removed.');showGuide(true)});
document.querySelector('#theme-list').addEventListener('click',e=>{const button=e.target.closest('[data-theme-toggle]');if(!button)return;const key=button.dataset.themeToggle;disabledThemes.has(key)?disabledThemes.delete(key):disabledThemes.add(key);localStorage.setItem('fake-cable-disabled-themes',JSON.stringify([...disabledThemes]));CHANNELS=sourceChannels();rebuildThemedChannels();saveLineup();state.current=null;renderStationPicker();render()});
document.addEventListener('keydown',e=>{if(document.querySelector('#welcome').style.display!=='none'){if(e.key==='Enter')document.querySelector('#start').click();return}if(document.querySelector('#setup').style.display==='block'){if(e.key==='Enter'&&document.activeElement===document.querySelector('#channel-search'))searchChannel();return}const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','enter'].includes(k))e.preventDefault();if(k==='g'||k==='escape')showGuide(!state.guide);else if(k==='f')document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();else if(k==='m'&&state.ready){state.muted=!state.muted;state.muted?state.player.mute():state.player.unMute();toast(state.muted?'MUTED':'SOUND ON')}else if(state.guide){if(k==='arrowup'){state.row=(state.row-1+CHANNELS.length)%CHANNELS.length;state.col=currentIndex(CHANNELS[state.row]);render()}if(k==='arrowdown'){state.row=(state.row+1)%CHANNELS.length;state.col=currentIndex(CHANNELS[state.row]);render()}if(k==='arrowleft')stepProgram(-1);if(k==='arrowright')stepProgram(1);if(k==='enter')tune()}else{if(k==='arrowup')tune(state.row+1);if(k==='arrowdown')tune(state.row-1);if(k==='enter'||k===' ')showBanner()}});
document.querySelector('#lineup-status').textContent=CHANNELS.some(c=>c.channelId)?`${CHANNELS.length} personal channels ready`:'Demo lineup · open Settings to add your channels';
if(stationPicker.length&&localStorage.getItem('fake-cable-lineup-version')!=='5'){document.querySelector('#lineup-status').textContent='Repairing and expanding your lineup…';buildChannels('Your lineup has been repaired.')}
let renderTimer=null;const rerenderGuide=()=>{clearTimeout(renderTimer);renderTimer=setTimeout(()=>{if(state.guide)render()},100)};window.addEventListener('resize',rerenderGuide);window.addEventListener('orientationchange',rerenderGuide);document.addEventListener('fullscreenchange',rerenderGuide);
const shared=decodeLineup(location.hash);if(shared?.channels)incomingLineup(shared);else if(shared?.error)document.querySelector('#lineup-status').textContent=shared.error;setInterval(tick,1000);tick();render();setTimeout(refreshStaleChannels,6000);
const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';document.head.appendChild(api);