export function guidePrograms(ch,start,end,current){const programs=[];for(let i=0;i<ch.schedule.length;i++){const program=ch.schedule[i];if(program.isCommercial){const spots=[program];while(ch.schedule[i+1]?.commercialBreakId===program.commercialBreakId)spots.push(ch.schedule[++i]);const currentSpot=spots.indexOf(current),entry={...program,title:'COMMERCIAL BREAK',source:`${spots.length} COMMERCIALS`,start:spots[0].start,end:spots.at(-1).end,duration:spots.at(-1).end-spots[0].start,_guideIndex:currentSpot>=0?ch.schedule.indexOf(current):ch.schedule.indexOf(spots[0]),_current:currentSpot>=0};if(entry.end>start&&entry.start<end)programs.push(entry)}else if(program.end>start&&program.start<end)programs.push({...program,_guideIndex:i,_current:program===current})}return programs}

export function createGuideController({getChannels,state,nowSec,currentIndex,fmtClock,esc,broadcastRemoteStatus}){
  function guideSlotWidth(){return Math.min(300,Math.max(190,window.innerWidth*.17))}
  function updateGuideNowLine(start=state.guideStart){if(!start)return;const timeline=document.querySelector('#timeline'),grid=document.querySelector('#grid'),label=timeline.querySelector('.time-label'),corner=timeline.querySelector('.timeline-corner'),marker=timeline.querySelector('.timeline-now-marker'),line=grid.querySelector('.guide-now-line');if(!label||!corner||!marker||!line)return;const left=corner.getBoundingClientRect().width+(nowSec()-start)*label.getBoundingClientRect().width/900;marker.style.left=left+'px';line.style.left=left+'px'}
  function updateGuideProgramProgress(){const now=nowSec();document.querySelectorAll('.program.current').forEach(program=>{const start=Number(program.dataset.start),duration=Number(program.dataset.duration);if(!Number.isFinite(start)||!Number.isFinite(duration)||duration<=0)return;program.style.setProperty('--progress',Math.max(0,Math.min(100,(now-start)/duration*100))+'%')})}
  function updateGuideProgramTextPins(){const scroller=document.querySelector('#grid-scroll');if(!scroller)return;const visibleLeft=scroller.scrollLeft;document.querySelectorAll('.program').forEach(program=>{const shift=Math.max(0,Math.min(visibleLeft-program.offsetLeft,program.offsetWidth-44));program.style.setProperty('--content-shift',shift+'px')})}
  function render(){const slotSeconds=900,start=Math.floor(nowSec()/slotSeconds)*slotSeconds-slotSeconds,end=start+slotSeconds*6;state.guideStart=start;const timeline=document.querySelector('#timeline');timeline.innerHTML='<div class="timeline-corner"></div>'+Array.from({length:6},(_,i)=>`<div class="time-label">${fmtClock(start+i*slotSeconds)}</div>`).join('')+'<div class="timeline-now-marker"><span>NOW</span></div>';const pxPerSec=(timeline.querySelector('.time-label')?.getBoundingClientRect().width||guideSlotWidth())/slotSeconds;
   const grid=document.querySelector('#grid');grid.innerHTML='';getChannels().forEach((ch,ri)=>{const row=document.createElement('div');row.className='channel-row'+(ri===state.row?' selected':'');row.dataset.row=ri;row.style.setProperty('--station',ch.color||'#52d9db');const current=ch.schedule[currentIndex(ch)],programs=guidePrograms(ch,start,end,current);row.innerHTML=`<div class="channel-num" data-tune="${ri}"><span class="channel-number">${String(ch.n).padStart(2,'0')}</span><small>${esc(ch.name)}</small></div><div class="programs"></div>`;const box=row.lastElementChild;programs.forEach(p=>{const idx=p._guideIndex,el=document.createElement('div'),programWidth=Math.max(2,(Math.min(p.end,end)-Math.max(p.start,start))*pxPerSec-4);el.className='program'+(p._current?' current':'')+(p.isCommercial?' commercial':'')+(ri===state.row&&idx===state.col?' focused':'')+(programWidth<130?' compact':'')+(programWidth<54?' micro':'');el.dataset.row=ri;el.dataset.col=idx;el.dataset.start=p.start;el.dataset.duration=p.duration;el.style.left=Math.max(0,(p.start-start)*pxPerSec)+'px';el.style.width=programWidth+'px';if(p._current)el.style.setProperty('--progress',Math.max(0,Math.min(100,(nowSec()-p.start)/p.duration*100))+'%');el.innerHTML=`<div class="program-title">${esc(p.title)}</div><div class="program-details"><span class="program-source">${esc(p.source)}</span><span class="program-time">${fmtClock(p.start)}</span></div>${p._current?'<div class="live">● LIVE</div><div class="program-progress"><i></i></div>':''}`;box.appendChild(el)});grid.appendChild(row)});grid.insertAdjacentHTML('beforeend','<div class="guide-now-line"></div>');state.guideCurrentSignature=getChannels().map(currentIndex).join('|');updateGuideNowLine(start);updateGuideProgramTextPins();updateSelection(false)}
  function ensureSelection(){const ch=getChannels()[state.row];if(state.col<0||state.col>=ch.schedule.length||ch.schedule[state.col].end<nowSec()-1800||ch.schedule[state.col].start>nowSec()+10800)state.col=currentIndex(ch)}
  function keepGuideRowVisible(row){const scroller=document.querySelector('#grid-scroll'),timeline=document.querySelector('#timeline');if(!scroller||!timeline)return;const rowBounds=row.getBoundingClientRect(),viewport=scroller.getBoundingClientRect(),visibleTop=Math.max(viewport.top,timeline.getBoundingClientRect().bottom),visibleBottom=viewport.bottom;if(rowBounds.top<visibleTop)scroller.scrollTop-=visibleTop-rowBounds.top;else if(rowBounds.bottom>visibleBottom)scroller.scrollTop+=rowBounds.bottom-visibleBottom}
  function updateSelection(scroll=true){ensureSelection();const ch=getChannels()[state.row],p=ch.schedule[state.col];document.querySelector('#selected-title').textContent=p.title;document.querySelector('#selected-meta').textContent=`CH ${String(ch.n).padStart(2,'0')} · ${ch.name} · ${fmtClock(p.start)}–${fmtClock(p.end)}`;document.querySelectorAll('.channel-row').forEach((r,i)=>r.classList.toggle('selected',i===state.row));document.querySelectorAll('.program').forEach(e=>e.classList.remove('focused'));const row=document.querySelectorAll('.channel-row')[state.row];if(row){const focused=row.querySelector(`.program[data-col="${state.col}"]`);focused?.classList.add('focused');if(scroll){focused?.scrollIntoView({block:'nearest',inline:'nearest'});keepGuideRowVisible(row)}}broadcastRemoteStatus()}

  return {render,updateGuideNowLine,updateGuideProgramProgress,updateGuideProgramTextPins,updateSelection};
}
