const BROADCAST_DATE_FORMATTER=new Intl.DateTimeFormat('en-US-u-ca-gregory-nu-latn',{timeZone:'America/New_York',year:'numeric',month:'numeric',day:'numeric'});
const EASTERN_OFFSET_FORMATTER=new Intl.DateTimeFormat('en-US-u-ca-gregory-nu-latn',{timeZone:'America/New_York',year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'});
function parts(formatter,date){return Object.fromEntries(formatter.formatToParts(date).filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]))}
function easternOffsetMs(utcMs){const p=parts(EASTERN_OFFSET_FORMATTER,new Date(utcMs));return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-utcMs}
export function dayStart(date=new Date()){const p=parts(BROADCAST_DATE_FORMATTER,new Date(date)),wallClockUtc=Date.UTC(p.year,p.month-1,p.day);return(wallClockUtc-easternOffsetMs(wallClockUtc))/1000}
export function hashString(value){let h=2166136261;for(const char of String(value)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function seededRandom(seed){let x=seed||1;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffled(items,random){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function rotated(items,index){return items.length?[...items.slice(index),...items.slice(0,index)]:[]}
export function seriesKey(show){return String(show[0]||'').toLowerCase().replace(/\b(?:episode|ep|part|chapter|season|vol(?:ume)?)\s*\d+\b/g,' ').replace(/\bs?\d{1,2}e\d{1,3}\b/g,' ').replace(/\b\d+\b/g,' ').replace(/[^a-z]+/g,' ').trim().split(/\s+/).filter(word=>word.length>2&&!['the','and','with','from','this','that'].includes(word)).slice(0,3).join(' ')}
function spreadSeries(items,random){const waiting=shuffled(items,random),out=[];while(waiting.length){const recent=new Set(out.slice(-2).map(seriesKey).filter(Boolean)),lastSource=out.at(-1)?.[1];let choices=waiting.map((show,index)=>({show,index})).filter(({show})=>!recent.has(seriesKey(show))&&show[1]!==lastSource);if(!choices.length)choices=waiting.map((show,index)=>({show,index})).filter(({show})=>show[1]!==lastSource);if(!choices.length)choices=waiting.map((show,index)=>({show,index}));const pick=choices[Math.floor(random()*choices.length)];out.push(pick.show);waiting.splice(pick.index,1)}return out}
export function programmedOrder(ch,cycle=0){const seed=hashString(`${ch.channelId||ch.name}:${cycle}`),random=seededRandom(seed),shows=[...new Map(ch.shows.filter(show=>show?.[2]).map(show=>[show[2],show])).values()];if(shows.length<2)return shows;const features=shows.filter(show=>(Number(show[3])||1800)>300),shorts=shows.filter(show=>(Number(show[3])||1800)<=300);if(features.length<3||!shorts.length)return spreadSeries(shows,random);const main=spreadSeries(features,random),breaks=spreadSeries(shorts,random),out=[];let shortIndex=0,nextBreak=2+Math.floor(random()*2);for(const show of main){out.push(show);if(out.filter(item=>features.includes(item)).length===nextBreak&&shortIndex<breaks.length){out.push(breaks[shortIndex++]);nextBreak+=2+Math.floor(random()*3)}}return out.concat(breaks.slice(shortIndex))}
export function makeSchedule(ch,{date=new Date(),commercials=[]}={}){const midnight=dayStart(date),out=[];if(!ch.shows?.length)return out;const anchorOffset=hashString(ch.channelId||ch.name)%2?1800:0,start=midnight-21600+anchorOffset,end=midnight+151200;let t=start,cycle=Math.floor(start/86400),order=programmedOrder(ch,cycle);order=rotated(order,Math.abs(hashString(ch.channelId||ch.name))%Math.max(1,order.length));let i=0,commercialPool=[],programsUntilBreak=2,breakNumber=0,recentIds=[],repeatGap=Math.min(Math.max(order.length-1,0),10);
 const resetCommercials=()=>{commercialPool=[...new Map(commercials.filter(show=>show?.[2]).map(show=>[show[2],show])).values()];const random=seededRandom(hashString(`commercials:${ch.channelId||ch.name}:${cycle}`));programsUntilBreak=2+Math.floor(random()*2)};
 resetCommercials();
 while(t<end){if(i>=order.length){order=programmedOrder(ch,++cycle);i=0;resetCommercials()}if(recentIds.includes(order[i]?.[2])){const nextFresh=order.findIndex((show,index)=>index>i&&!recentIds.includes(show[2]));if(nextFresh>i)[order[i],order[nextFresh]]=[order[nextFresh],order[i]]}const s=order[i++];if(!s)break;recentIds.push(s[2]);if(recentIds.length>repeatGap)recentIds.shift();const duration=Math.max(Number(s[3])||1800,60);out.push({title:s[0],source:s[1],id:s[2],duration,start:t,end:t+duration,sourceChannelId:s[4]});t+=duration;if(commercialPool.length&&!--programsUntilBreak&&t<end){const breakId=`${ch.channelId||ch.name}:${cycle}:${breakNumber++}`,random=seededRandom(hashString(breakId)),breakSize=Math.min(commercialPool.length,2+Math.floor(random()*2)),spots=shuffled(commercialPool,random).slice(0,breakSize),breakDuration=spots.reduce((sum,spot)=>sum+Math.max(Number(spot[3])||60,15),0);if(t+breakDuration<end){spots.forEach((commercial,position)=>{const commercialDuration=Math.max(Number(commercial[3])||60,15);out.push({title:commercial[0],source:commercial[1],id:commercial[2],duration:commercialDuration,start:t,end:t+commercialDuration,isCommercial:true,commercialBreakId:breakId,commercialPosition:position+1,commercialCount:spots.length});t+=commercialDuration})}programsUntilBreak=2+Math.abs(hashString(`${breakId}:${t}`))%2}}return out}
export function currentIndexAt(ch,time=Date.now()/1000){const index=ch.schedule.findIndex(program=>program.start<=time&&program.end>time);return index<0?0:index}
